[package]
name = "ddb"
version = "0.1.0"
authors = ["RobinZhang <yanbin.zhang@dolphindb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ddb"
crate-type = ["rlib"]

[dependencies]
libc = "0.2.0"
rand = "0.5"


